name: 'Install binary'
description: 'Install binaries from the stellar/binaries repo'
inputs:
  name:
    required: true
  version:
    required: true
  ref:
    required: false
runs:
  using: "composite"
  steps:
  - name: Determine Install Path
    shell: bash
    run: |
      # Tools beginning with 'cargo-' are intended to be used as a plugin for
      # cargo. For some reason in GitHub Actions Window's runners cargo only
      # finds plugins installed in the .cargo/bin directory, and not other bin
      # directories even if they are located on the path.
      if [[ "${{ inputs.name }}" == cargo-* ]]; then
        echo "INSTALL_PATH=$HOME/.cargo/bin" >> $GITHUB_ENV
      else
        echo "INSTALL_PATH=$HOME/.local/bin" >> $GITHUB_ENV
      fi
  - name: Setup Install Location
    shell: bash
    run: |
      mkdir -p $INSTALL_PATH
      echo "$INSTALL_PATH" >> $GITHUB_PATH
  - shell: bash
    env:
      REF: ${{ github.action_ref }}
    run: |
      file="${{ inputs.name }}-${{ inputs.version }}-${{ runner.os }}-${{ runner.arch }}.tar.gz"
      ref="${{ inputs.ref || env.REF }}"
      curl -fL https://github.com/stellar/binaries/releases/download/$ref/$file | tar xvz -C $INSTALL_PATH
